version: '3'

services:
  portainer:
    image: portainer/portainer-ee:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data:/data
    expose:
      - 9000
    networks:
      - ingress

networks:
  ingress:
    name: ingress
