version: '3.9'
services:
  guessaiword:
    env_file: .env
    image: shutupandtakemy.codes/guessaiword:latest
    restart: always
    user: "1000:1000"
    command: java -jar build.jar --spring.datasource.url=jdbc:mariadb://gaiw-db:3306/guessaiword --spring.datasource.driverClassName=org.mariadb.jdbc.Driver --spring.datasource.username=guessaiword --spring.datasource.password=${MARIADB_PASSWORD} --guessaiword.ai.model=gpt-4
    networks:
      - ingress
      - guessaiword
    environment:
      - AI_API_KEY=${AI_API_KEY}
    expose:
      - 8080
  gaiw-db:
    env_file: .env
    image: mariadb
    restart: always
    user: "1000:1000"
    networks:
      - guessaiword
      - maxscale
    volumes:
      - ./data:/var/lib/mysql:rw
    expose:
      - 3306
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=guessaiword
      - MARIADB_USER=guessaiword
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

networks:
  ingress:
    name: ingress
  guessaiword:
  maxscale:
    name: maxscale
