version: "3.9"
services:
  caddy:
    image: shutupandtakemy.codes/caddy
    restart: always
    user: 1000:1000
    networks:
      - ingress
    volumes:
      - ./data:/data
      - ./config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /var/www:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "2022:2022/tcp"
      - "25565:25565/tcp"

networks:
  ingress:
    driver: bridge
    name: ingress
