version: "3.9"
services:
  caddy:
    image: shutupandtakemy.codes/caddy
    restart: always
    user: 1000:1000
    networks:
      - ingress
      - caddy-monitor
    volumes:
      - ./data:/data
      - ./config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./templates:/etc/caddy/templates
      - /var/www:/var/www
      - /mnt/minecraft-backups:/mnt/minecraft-backups
      - /var/log/caddy:/var/log/caddy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
      - CADDY_ADMIN=0.0.0.0:2019
    expose:
      - "2019"
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"

networks:
  ingress:
    driver: bridge
    name: ingress
  caddy-monitor:
    name: caddy-monitor
