version: '3.9'
services:
  regdisplay:
    restart: always
    image: shutupandtakemy.codes/reg
    networks:
      - ingress
      - registry
    expose:
      - 8080
    env_file: .env
    command: server -u display -p ${DISPLAY_PASSWORD} -f -r https://r.shutupandtakemy.codes --interval 0h1m0s
  registryro:
    restart: always
    image: registry:2
    user: "1000:1000"
    networks:
      - ingress
      - registry
    expose:
      - 5000
    volumes:
      - ./data:/var/lib/registry:ro
      - ./auth:/auth:ro
  registry:
    restart: always
    image: registry:2
    user: "1000:1000"
    networks:
      - ingress
      - registry
    expose:
      - 5000
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth

networks:
  ingress:
    name: ingress
  registry:
