version: '3.9'
services:
  pluto3:
    build: ./pluto3
    restart: always
    networks:
      - nginx
      - pluto3
    volumes:
      - ./serviceAccount.json:/etc/serviceAccount.json:ro
    env_file: .env
    environment:
      - PORT=3300
      - AI_BACKEND_URL=http://example.com
      - DATABASE_HOST=mariadb
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/serviceAccount.json
    expose:
      - 3300
  pluto3-adminer:
    image: adminer
    restart: always
    networks:
      - nginx
      - pluto3
    expose:
      - 8080
  mariadb:
    image: mariadb
    restart: always
    networks:
      - pluto3
    volumes:
      - ./data:/var/lib/mysql:rw
    expose:
      - 3306
    env_file: .env
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=h3b1
      - MARIADB_USER=h3b1
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}

networks:
  nginx:
    name: nginx
  pluto3:
