version: "3.9"
services:
  caddy:
    image: shutupandtakemy.codes/caddy:arm64
    restart: always
    user: 1002:1002
    networks:
      - ingress
    volumes:
      - ./data:/data
      - ./config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./templates:/etc/caddy/templates
      - /var/www:/var/www
      - /home/pmh/minecraft-backups:/mnt/minecraft-backups
      - /var/log/caddy:/var/log/caddy
    env_file:
      - .env
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"

networks:
  ingress:
    driver: bridge
    name: ingress
