version: '3.9'
services:
  sowon-frontend:
    image: shutupandtakemy.codes/sowonpay-frontend
    restart: always
    networks:
      - ingress
      - sowonpay
    expose:
      - 8080
  sowon-backend:
    image: shutupandtakemy.codes/sowonpay-backend
    restart: always
    volumes:
      - ./.env:/app/.env:ro
    networks:
      - ingress
      - sowonpay
    expose:
      - 8080
  sowonpay-db:
    image: mariadb
    restart: always
    networks:
      - sowonpay
      - maxscale
    volumes:
      - ./data:/var/lib/mysql:rw
    expose:
      - 3306
    env_file: .env
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=sowonpay
      - MARIADB_USER=sowonpay
      - MARIADB_PASSWORD=${DB_PASSWD}

networks:
  ingress:
    name: ingress
  sowonpay:
  maxscale:
    name: maxscale
