version: '3.9'
services:
  wiki-frontend:
    image: mediawiki
    restart: always
    volumes:
      - ./image:/var/www/html/images
      - ./Neptune:/var/www/html/skins/Neptune
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./.htaccess:/var/www/html/.htaccess
      - ./extensions/CSS:/var/www/html/extensions/CSS
      - ./extensions/YouTube:/var/www/html/extensions/YouTube
    networks:
      - ingress
      - wiki
    expose:
      - 80
  wiki-db:
    image: mariadb
    restart: always
    networks:
      - wiki
      - maxscale
    volumes:
      - ./data:/var/lib/mysql:rw
    expose:
      - 3306
    env_file: .env
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=wiki
      - MARIADB_USER=wiki
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

networks:
  ingress:
    name: ingress
  wiki:
  maxscale:
    name: maxscale

volumes:
  images:
