version: '3.9'
services:
  speedtest:
    image: adolfintel/speedtest:latest
    restart: always
    networks:
      - ingress
    expose:
      - 80
    environment:
      - 'TITLE=SHIT! SERONET SPEED'
      - 'DISABLE_IPINFO=true'
      - 'MODE=standalone'

networks:
  ingress:
    name: ingress
