version: '2'

services:
  nextcloud:
    image: nextcloud
    restart: always
    user: 1000:1000
    networks:
      - nginx
      - nextcloud
    expose:
      - 80
    volumes:
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/apps:/var/www/html/apps
      - /mnt/nextcloud:/var/www/html/data
    env_file: .env
    environment:
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

  db:
    image: mariadb
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - nextcloud
    expose:
      - 3306
    env_file: .env
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=nextcloud
      - MARIADB_USER=nextcloud
      - MARIADB_PASSWORD=${DATABASE_PASSWORD}

  redis:
    image: redis
    restart: always
    expose:
      - 6379
    networks:
      - nextcloud

  nextcloud-adminer:
    image: adminer
    restart: always
    networks:
      - nginx
      - nextcloud
    expose:
      - 8080

networks:
  nginx:
    name: nginx
  nextcloud:

