version: "3.9"
services:
  mc-proxy:
    image: ghcr.io/pmh-only/velocity
    user: 1002:1002
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/proxy:/app/:rw
    ports:
      - '25565:25565/tcp'
  mc-lobby:
    image: ghcr.io/pmh-only/paper
    user: 1002:1002
    command: -Xms1G -Xmx1G
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
      - ingress
    volumes:
      - ./volumes/lobby:/app/:rw
    expose:
      - 25565
      - 8100
  mc-creative:
    image: ghcr.io/pmh-only/paper
    user: 1002:1002
    command: -Xms1G -Xmx1G
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/creative:/app/:rw
    expose:
      - 25565
  mc-minigames:
    image: ghcr.io/pmh-only/paper
    user: 1002:1002
    command: -Xms2G -Xmx2G
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/minigames:/app/:rw
    expose:
      - 25565
  mc-survival:
    image: ghcr.io/pmh-only/paper
    user: 1002:1002
    command: -Xms1G -Xmx1G
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/survival:/app/:rw
    expose:
      - 25565
  mc-db:
    image: mariadb
    restart: always
    user: 1002:1002
    networks:
      - minecraft
    volumes:
      - ./data:/var/lib/mysql:rw
    expose:
      - 3306
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=minecraft
      - MARIADB_USER=minecraft
      - MARIADB_PASSWORD=minecraft

networks:
  ingress:
    name: ingress
    external: true
  minecraft:
    driver: bridge
