version: "3.9"
services:
  nginx:
    image: nginx:mainline
    restart: always
    ipc: host
    networks:
      - nginx
    volumes:
      - ./conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./conf:/etc/nginx/:ro
      - /etc/letsencrypt:/certs/:ro
      - /var/www:/var/www:rw
      - /var/log/nginx:/var/log/nginx:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
      - "25565:25565/tcp"

networks:
  nginx:
    driver: bridge
    name: nginx
