version: "3.9"
services:
  mc-proxy:
    image: ghcr.io/pmh-only/velocity
    user: 1000:1000
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/proxy:/app/:rw
    ports:
      - '25565:25565/tcp'
  mc-lobby:
    image: ghcr.io/pmh-only/paper
    user: 1000:1000
    command: -Xms1G -Xmx1G
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
      - ingress
    volumes:
      - ./volumes/lobby:/app/:rw
    expose:
      - 25565
      - 8100
      - 9100
  mc-creative:
    image: ghcr.io/pmh-only/paper
    user: 1000:1000
    command: -Xms1G -Xmx1G
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/creative:/app/:rw
    expose:
      - 25565
      - 9100
  mc-minigames:
    image: ghcr.io/pmh-only/paper
    user: 1000:1000
    command: -Xms2G -Xmx2G
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/minigames:/app/:rw
    expose:
      - 25565
      - 9100
  mc-survival:
    image: ghcr.io/pmh-only/paper
    user: 1000:1000
    command: -Xms1G -Xmx1G
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/survival:/app/:rw
    expose:
      - 25565
      - 9100
  mc-db:
    image: mariadb
    restart: always
    user: 1000:1000
    networks:
      - minecraft
      - maxscale
    volumes:
      - ./data:/var/lib/mysql:rw
    expose:
      - 3306
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=minecraft
      - MARIADB_USER=minecraft
      - MARIADB_PASSWORD=minecraft
  mc-nginx:
    image: nginx:mainline
    restart: always
    networks:
      - minecraft
      - mc-monitor
    volumes:
      - ./conf:/etc/nginx/:ro
      - /var/www:/var/www:rw
      - /mnt/minecraft-backups:/var/backups:rw
    expose:
      - 9100
      - 9101
      - 9104
      - 9106
      - 9107

networks:
  ingress:
    driver: bridge
    name: ingress
  minecraft:
    driver: bridge
  mc-monitor:
    name: mc-monitor
  maxscale:
    name: maxscale
