version: "3.9"
services:
  mc-proxy:
    image: eclipse-temurin:18-alpine
    user: 1000:1000
    working_dir: /app
    command:
      - java
      - -XX:+UseG1GC
      - -XX:G1HeapRegionSize=4M
      - -XX:+UnlockExperimentalVMOptions
      - -XX:+ParallelRefProcEnabled
      - -XX:+AlwaysPreTouch
      - -XX:MaxInlineLevel=15
      - -Dvelocity.packet-decode-logging=true
      - -jar
      - server.jar
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/proxy:/app/:rw
    expose:
      - '25565'
  mc-lobby:
    image: eclipse-temurin:18-alpine
    user: 1000:1000
    working_dir: /app
    command:
      - java
      - -Xms1G
      - -Xmx1G
      - -XX:+UseG1GC
      - -XX:+ParallelRefProcEnabled
      - -XX:MaxGCPauseMillis=200
      - -XX:+UnlockExperimentalVMOptions
      - -XX:+DisableExplicitGC
      - -XX:+AlwaysPreTouch
      - -XX:G1NewSizePercent=30
      - -XX:G1MaxNewSizePercent=40
      - -XX:G1HeapRegionSize=8M
      - -XX:G1ReservePercent=20
      - -XX:G1HeapWastePercent=5
      - -XX:G1MixedGCCountTarget=4
      - -XX:InitiatingHeapOccupancyPercent=15
      - -XX:G1MixedGCLiveThresholdPercent=90
      - -XX:G1RSetUpdatingPauseTimePercent=5
      - -XX:SurvivorRatio=32
      - -XX:+PerfDisableSharedMem
      - -XX:MaxTenuringThreshold=1
      - -Dusing.aikars.flags=https://mcflags.emc.gs
      - -Daikars.new.flags=true
      - -jar
      - server.jar
      - --nogui
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/lobby:/app/:rw
    expose:
      - 25565
      - 8100
      - 9100
  mc-creative:
    image: eclipse-temurin:18-alpine
    user: 1000:1000
    working_dir: /app
    command:
      - java
      - -Xms1G
      - -Xmx1G
      - -XX:+UseG1GC
      - -XX:+ParallelRefProcEnabled
      - -XX:MaxGCPauseMillis=200
      - -XX:+UnlockExperimentalVMOptions
      - -XX:+DisableExplicitGC
      - -XX:+AlwaysPreTouch
      - -XX:G1NewSizePercent=30
      - -XX:G1MaxNewSizePercent=40
      - -XX:G1HeapRegionSize=8M
      - -XX:G1ReservePercent=20
      - -XX:G1HeapWastePercent=5
      - -XX:G1MixedGCCountTarget=4
      - -XX:InitiatingHeapOccupancyPercent=15
      - -XX:G1MixedGCLiveThresholdPercent=90
      - -XX:G1RSetUpdatingPauseTimePercent=5
      - -XX:SurvivorRatio=32
      - -XX:+PerfDisableSharedMem
      - -XX:MaxTenuringThreshold=1
      - -Dusing.aikars.flags=https://mcflags.emc.gs
      - -Daikars.new.flags=true
      - -jar
      - server.jar
      - --nogui
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/creative:/app/:rw
    expose:
      - 25565
      - 9100
  mc-survival:
    image: eclipse-temurin:18-alpine
    user: 1000:1000
    working_dir: /app
    command:
      - java
      - -Xms1G
      - -Xmx1G
      - -XX:+UseG1GC
      - -XX:+ParallelRefProcEnabled
      - -XX:MaxGCPauseMillis=200
      - -XX:+UnlockExperimentalVMOptions
      - -XX:+DisableExplicitGC
      - -XX:+AlwaysPreTouch
      - -XX:G1NewSizePercent=30
      - -XX:G1MaxNewSizePercent=40
      - -XX:G1HeapRegionSize=8M
      - -XX:G1ReservePercent=20
      - -XX:G1HeapWastePercent=5
      - -XX:G1MixedGCCountTarget=4
      - -XX:InitiatingHeapOccupancyPercent=15
      - -XX:G1MixedGCLiveThresholdPercent=90
      - -XX:G1RSetUpdatingPauseTimePercent=5
      - -XX:SurvivorRatio=32
      - -XX:+PerfDisableSharedMem
      - -XX:MaxTenuringThreshold=1
      - -Dusing.aikars.flags=https://mcflags.emc.gs
      - -Daikars.new.flags=true
      - -jar
      - server.jar
      - --nogui
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
    volumes:
      - ./volumes/survival:/app/:rw
    expose:
      - 25565
      - 9100
  mariadb:
    image: mariadb
    restart: always
    user: 1000:1000
    networks:
      - minecraft
    volumes:
      - ./data:/var/lib/mysql:rw
    expose:
      - 3306
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_DATABASE=minecraft
      - MARIADB_USER=minecraft
      - MARIADB_PASSWORD=minecraft
  mc-nginx:
    image: nginx:mainline
    restart: always
    networks:
      - minecraft
      - ingress
      - mc-monitor
    volumes:
      - ./conf:/etc/nginx/:ro
      - /var/www:/var/www:rw
      - /mnt/minecraft-backups:/var/backups:rw
    expose:
      - 25565
      - 9100
      - 9101
      - 9104
      - 9106

networks:
  ingress:
    driver: bridge
    name: ingress
  minecraft:
    driver: bridge
  mc-monitor:
    name: mc-monitor
