version: '3'

services:
  ghost:
    image: ghost:alpine
    restart: always
    user: 1000:1000
    env_file:
      - .env
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: ghost
      database__connection__password: ghost
      database__connection__database: ghost
      mail__transport: SMTP
      mail__options__service: Google
      mail__options__host: smtp.gmail.com
      mail__options__port: 587
      mail__options__auth__user: ${GMAIL_USERNAME}
      mail__options__auth__pass: ${GMAIL_PASSWORD}
      mail__from: "'Minhyeok Park' <pmh_only@pmh.codes>"
      admin__url: https://admin.pmh.codes
      adapters__tenor__googleApiKey: ${TENOR_KEY}
      url: https://pmh.codes
    volumes:
      - ./data/content:/var/lib/ghost/content:rw
    expose:
      - 2368
    networks:
      - ingress
      - ghost
  db:
    image: mysql:8
    restart: always
    user: "1000:1000"
    networks:
      - ghost
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    expose:
      - 3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost

networks:
  ingress:
    name: ingress
  ghost:
