version: '3.9'
services:
  mntserver:
    image: shutupandtakemy.codes/djs-bot-for-my-server:latest
    restart: always
    user: 1000:1000
    env_file: .env
    environment:
      DISCORD_TOKEN: $DISCORD_TOKEN
      ENVIROMENT_DEV_GUILD: $ENVIROMENT_DEV_GUILD
      OPENAI_API_KEY: $OPENAI_API_KEY
